ribbon:
    eureka:
        enabled: false
server:
    port: 8085
zuul:
    sensitiveHeaders: Cookie,Set-Cookie
    routes:
        auditChecklist:
            serviceId: auditChecklist
            url: http://52.66.214.49:9100/
        auditSeverity:
            serviceId: auditSeverity
            url: http://13.233.186.180:9200/
        auditBenchmark:
            serviceId: auditBenchmark
            url: http://13.232.12.127:9300/
        auditAuthentication:
            serviceId: auditAuthentication
            url: http://13.235.16.176:9400/
           
            
           
