ribbon:
    eureka:
        enabled: false
server:
    port: 8085
zuul:
    sensitiveHeaders: Cookie,Set-Cookie
    routes:
        auditChecklist:
            serviceId: auditChecklist
            url: http://65.0.119.240:9100/
        auditSeverity:
            serviceId: auditSeverity
            url: http://3.108.255.15:9200/
        auditBenchmark:
            serviceId: auditBenchmark
            url: http://3.108.2.65:9300/
        auditAuthentication:
            serviceId: auditAuthentication
            url: http://13.235.58.76:9400/
           
            
           
